### ISSUE TITLE
log.Exitf changed to log.Fatalf in new Go release

### ISSUE THREAD

**Issue by ziutek** [knieriem/markdown#2]
8g -o _go_.8 parser.leg.go doc.go markdown.go output.go 
parser.leg.go:12344: undefined: log.Exitf
markdown.go:61: undefined: log.Exitf
output.go:184: undefined: log.Exitf
output.go:226: undefined: log.Exitf
make: **\* [_go_.8] Error 1
--- exit status 2

**Comment by knieriem** [comment]
Thanks, fixed.
