### ISSUE TITLE
Please don't log.Fatalf

### ISSUE THREAD

**Issue by peterbourgon** [knieriem/markdown#5]
If I give an empty buffer to Markdown(), it will log.Fatalf with "unexpected end of file". Please just return an error instead! I don't want my program to terminate on bad input (or whatever else).

**Comment by knieriem** [comment]
`tip' now contains a changeset that should fix this issue. [The old implementation treated a parse error as an internal
bug which should never occur, hence the log.Fatal. This was too strict, as certain valid input, like an empty
string or a number of spaces also triggers a parse error.]

**Comment by peterbourgon** [comment]
Cool, works for me!

Markdown on an empty string produces `\n` -- is that desired?

**Comment by knieriem** [comment]
It is the consequence of [`func (f *htmlOut) Finish(): f.WriteByte('\n')`](https://github.com/knieriem/markdown/blob/master/output.go#L59).

It might not be desired (I wondered myself yesterday, when I tested it), but it produces
the same output as the [C-version](https://github.com/jgm/peg-markdown).
The original Perl Markdown program also writes an '\n' for empty input.

One could easily skip the extra '\n' in case there has been no output before, though.
If you think this would be preferable, I can change it.

**Comment by peterbourgon** [comment]
It's totally inconsequential, just a test case for me. If other implementations roll with a `\n`, that's as good a reason as any to keep it. Thanks for your quick responses!
