### ISSUE TITLE
Rendering embedded <pre> tags discards data following closing tag

### ISSUE THREAD

**Issue by akrennmair** [knieriem/markdown#6]
Hi,

When I render Markdown that contains embedded HTML with &lt;pre&gt; and &lt;/pre&gt; tags, all the data that follows the closing </pre> tag isn't rendered at all. This example demonstrates the problem: https://gist.github.com/3146849

**Comment by knieriem** [comment]
Thanks for your report. The behaviour was caused by an incomplete change to the parser generator I did some time ago (https://github.com/knieriem/peg/commit/9d1d6e05). It should be fixed by the two most recent revisions.

**Comment by akrennmair** [comment]
Thanks for the quick response! After a go get -u, it now works as expected.
