### ISSUE TITLE
question ?

### ISSUE THREAD

**Issue by bussiere** [knieriem/markdown#8]
how to parse just a string please ?
markdown.ToHTML(lecture)

give me ::
cannot use lecture (type string) as type markdown.Writer in function argument:
    string does not implement markdown.Writer (missing Write method)

regards
Bussiere

**Comment by BurntSushi** [comment]
The public API could really use a convenience function to run markdown on a string, but this should do the trick:

``` go
var mparser = markdown.NewParser(nil)

func toMarkdown(s string) string {
    src := strings.NewReader(s)
    dst := new(bytes.Buffer)
    mparser.Markdown(src, markdown.ToHTML(dst))
    return dst.String()
}
```

**Comment by knieriem** [comment]
I'm sorry, but the email answer I wrote on last Wednesday somehow
hasn't left my computer.

I agree, there could be a convenience function, e.g. MarkdownString(s string).
